type: object
properties:
  openapi:
    type: object
    properties:
      validateRequest:
        type: boolean
        default: true
        description: Enable/disable request validation
      validateResponse:
        type: boolean
        default: true
        description: Enable/disable request validation
  security:
    type: object
    properties:
      jwtExpiresAfter:
        description: Validity duration of login tokens, in seconds
        default: 604800
        type: integer
      jwtPublicKeyFile:
        description: Path to the public rsa key used for authentication
        default: res/jwt-pubkey.pem
        type: string
      jwtPrivateKeyFile:
        description: Path to the private rsa key used for authentication
        default: res/jwt-privkey.pem
        type: string
  DB:
    type: object
    description: Database configuration object
    properties:
      user:
        type: string
        description: Username for database authentication
      pass:
        type: string
        description: Password for database authentication
      database:
        type: string
        description: Database schema to connect to
      host:
        type: string
        description: Hostname of the database server
        default: 127.0.0.1
      port:
        type: integer
        description: Port the database server listens on
        default: 3306
  options:
    type: object
    properties:
      dataPath:
        type: string
        description: Path containing shared resources
        default: /usr/share/grammm/common
      propnames:
        type: string
        description: File containing list of named properties. Path is relative to `dataPath`.
        default: propnames.txt
      portrait:
        type: string
        description: File containing default portrait image. Path is relative to `dataPath`.
        default: admin/api/portrait.jpg
      domainStoreRatio:
        type: integer
        description: Mysterious storage factor for `domain.maxSize`
        minimum: 1
        maximum: 999
        default: 10
      domainPrefix:
        type: string
        description: Path to store domain home directories in
        default: /d-data/
      userPrefix:
        type: string
        description: Path to store user home directories in
        default: /u-data/
      exmdbHost:
        type: string
        description: Name or IP address of the exmdb service provider
        default: '::1'
      exmdbPort:
        type: string
        description: Port or service name of the exmdb service provider
        default: '5000'
      domainStorageLevels:
        type: integer
        description: Number of sub-directory levels to use for domain storage
        minimum: 1
        maximum: 5
        default: 1
      userStorageLevels:
        type: integer
        description: Number of sub-directory levels to use for user storage
        minimum: 1
        maximum: 5
        default: 2
      domainAcceleratedStorage:
        type: string
        description: Path for accelerated domain storage
        nullable: true
        default: null
      userAcceleratedStorage:
        type: string
        description: Path for accelerated user storage
        nullable: true
        default: null
      dashboard:
        description: Configuration of the dashboard
        type: object
        properties:
          services:
            type: array
            description: List of services to monitor
            items:
              type: object
              properties:
                unit:
                  type: string
                  description: Name of the service
                name:
                  type: string
                  description: Optional alternative display name
      licenseFile:
        type: string
        description: Location of the license certificate. Must be writable by the server.
      fileUid:
        oneOf:
          - type: string
            description: Change ownership of created files to this user (name)
          - type: integer
            description: Change ownership of created files to this user (ID)
      fileGid:
        oneOf:
          - type: string
            description: Change ownership of created files to this group (name)
          - type: integer
            description: Change ownership of created files to this group (ID)
      filePermissions:
        oneOf:
          - type: integer
            description: Permission bitmask of newly created files
          - type: string
            description: Permission bitmask of newly created files
      antispamUrl:
          type: string
          default: 'http://127.0.0.1:11334'
          description: URL of the grammm-antispam backend
      antispamEndpoints:
          type: array
          description: List of allowed endpoints to proxy to grammm-antispam
          default: ["stat", "graph", "errors"]
          items:
            type: string
  mconf:
    description: Options for managed configurations
    type: object
    properties:
      fileUid:
          oneOf:
            - type: string
              description: Change ownership of created files to this user (name)
            - type: integer
              description: Change ownership of created files to this user (ID)
      fileGid:
        oneOf:
          - type: string
            description: Change ownership of created files to this group (name)
          - type: integer
            description: Change ownership of created files to this group (ID)
      filePermissions:
        oneOf:
          - type: integer
            description: Permission bitmask of newly created files
          - type: string
            description: Permission bitmask of newly created files
      ldapPath:
        type: string
        description: Path to the ldap configuration file
      authmgrPath:
        type: string
        description: Path to the authmgr configuration file
  logs:
    description: Associative list of log files to expose
    type: object
    additionalProperties:
      type: object
      required: [source]
      properties:
        format:
          type: string
          description: File format. Currently only `journald` is supported.
          enum: [journald]
          default: journald
        source:
          type: string
          description: Name of the journald unit
