type: object
properties:
  openapi:
    type: object
    properties:
      validateRequest:
        type: boolean
        default: true
        description: Enable/disable request validation
      validateResponse:
        type: boolean
        default: true
        description: Enable/disable request validation
  security:
    type: object
    properties:
      jwtExpiresAfter:
        description: Validity duration of login tokens, in seconds
        default: 604800
        type: integer
      jwtPublicKeyFile:
        description: Path to the public rsa key used for authentication
        default: res/jwt-pubkey.pem
        type: string
      jwtPrivateKeyFile:
        description: Path to the private rsa key used for authentication
        default: res/jwt-privkey.pem
        type: string
  DB:
    type: object
    description: Database configuration object
    properties:
      user:
        type: string
        description: Username for database authentication
      pass:
        type: string
        description: Password for database authentication
      database:
        type: string
        description: Database schema to connect to
      host:
        type: string
        description: Hostname of the database server
        default: 127.0.0.1
      port:
        type: integer
        description: Port the database server listens on
        default: 3306
  options:
    type: object
    properties:
      dataPath:
        type: string
        description: Path containing shared resources
        default: /usr/share/grammm/common
      propnames:
        type: string
        description: File containing list of named properties. Path is relative to `dataPath`.
        default: propnames.txt
      portrait:
        type: string
        description: File containing default portrait image. Path is relative to `dataPath`.
        default: admin/api/portrait.jpg
      domainStoreRatio:
        type: integer
        description: Mysterious storage factor for `domain.maxSize`
        minimum: 1
        maximum: 999
        default: 10
      domainPrefix:
        type: string
        description: Path to store domain home directories in
        default: /d-data/
      userPrefix:
        type: string
        description: Path to store user home directories in
        default: /u-data/
      domainStorageLevels:
        type: integer
        description: Number of sub-directory levels to use for domain storage
        minimum: 1
        maximum: 5
        default: 1
      userStorageLevels:
        type: integer
        description: Number of sub-directory levels to use for user storage
        minimum: 1
        maximum: 5
        default: 2
      domainAcceleratedStorage:
        type: string
        description: Path for accelerated domain storage
        nullable: true
        default: null
      userAcceleratedStorage:
        type: string
        description: Path for accelerated user storage
        nullable: true
        default: null
      dashboard:
        description: Configuration of the dashboard
        type: object
        properties:
          services:
            type: array
            description: List of services to monitor
            items:
              type: object
              properties:
                unit:
                  type: string
                  description: Name of the service
                name:
                  type: string
                  description: Optional alternative display name
