type: object
properties:
  openapi:
    type: object
    properties:
      validateRequest:
        type: boolean
        default: true
        description: Enable/disable request validation
      validateResponse:
        type: boolean
        default: true
        description: Enable/disable request validation
  security:
    type: object
    properties:
      jwtExpiresAfter:
        description: Validity duration of login tokens, in seconds
        default: 604800
        type: integer
      jwtPublicKeyFile:
        description: Path to the public rsa key used for authentication
        default: res/jwt-pubkey.pem
        type: string
      jwtPrivateKeyFile:
        description: Path to the private rsa key used for authentication
        default: res/jwt-privkey.pem
        type: string
  DB:
    type: object
    description: Database configuration object
    properties:
      user:
        type: string
        description: Username for database authentication
      pass:
        type: string
        description: Password for database authentication
      database:
        type: string
        description: Database schema to connect to
      host:
        type: string
        description: Hostname of the database server
        default: 127.0.0.1
      port:
        type: integer
        description: Port the database server listens on
        default: 3306
  options:
    type: object
    properties:
      dataPath:
        type: string
        description: Path containing shared resources
        default: /usr/share/grammm/common
      propnames:
        type: string
        description: File containing list of named properties. Path is relative to `dataPath`.
        default: propnames.txt
      portrait:
        type: string
        description: File containing default portrait image. Path is relative to `dataPath`.
        default: admin/api/portrait.jpg
      domainStoreRatio:
        type: integer
        description: Mysterious storage factor for `domain.maxSize`
        minimum: 1
        maximum: 999
        default: 10
      domainPrefix:
        type: string
        description: Path to store domain home directories in
        default: /d-data/
      userPrefix:
        type: string
        description: Path to store user home directories in
        default: /u-data/
      domainStorageLevels:
        type: integer
        description: Number of sub-directory levels to use for domain storage
        minimum: 1
        maximum: 5
        default: 1
      userStorageLevels:
        type: integer
        description: Number of sub-directory levels to use for user storage
        minimum: 1
        maximum: 5
        default: 2
      domainAcceleratedStorage:
        type: string
        description: Path for accelerated domain storage
        nullable: true
        default: null
      userAcceleratedStorage:
        type: string
        description: Path for accelerated user storage
        nullable: true
        default: null
      dashboard:
        description: Configuration of the dashboard
        type: object
        properties:
          services:
            type: array
            description: List of services to monitor
            items:
              type: object
              properties:
                unit:
                  type: string
                  description: Name of the service
                name:
                  type: string
                  description: Optional alternative display name
      licenseFile:
        type: string
        description: Location of the license certificate. Must be writable by the server.
  ldap:
    type: object
    properties:
      connection:
        type: object
        required: [server]
        properties:
          server:
            type: string
            description: Address of the LDAP server to connect to
          bindUser:
            type: string
            description: DN of the user to perform initial bind with
          bindPass:
            type: string
            description: Password for bindUser
      baseDn:
        type: string
        description: Base DN to use for user search
      starttls:
        type: boolean
        description: Whether to initiate a StartTLS connection
      objectID:
        type: string
        description: Name of an attribute that uniquely idetifies an LDAP object
      users:
        type: object
        required: [username, searchAttributes]
        description: Configuration for user search
        properties:
          username:
            type: string
            description: Name of the attribute that corresponds to the username (e-mail address)
            default: uid
          filters:
            type: array
            description: List of additional filter expressions to use for user search
            items:
              type: string
              example: 'objectclass=person'
          templates:
            type: array
            description: List of mapping templates to use
            items:
              type: string
              description: Name of a template defined in res/ldapTemplates.yaml
          attributes:
            type: object
            description: LDAP attribute -> PropTag mapping to used for LDAP import. Any mappings specified take precendence over active templates
            additionalProperties:
              type: string
              description: Name of the PropTag the atribute maps to
          defaultQuota:
            type: integer
            description: Storage quota of imported users if no mapping exists
          searchAttributes:
            type: array
            description: List of attributes to use for searching
            items:
              type: string
              description: LDAP attribute name
